public with sharing class OpenStreetMapConstants {
    public static final String URL_PARAM_CITY = '?city=';
    public static final String URL_PARAM_COUNTRY = '&country=';
    public static final String URL_SUFFIX = '&format=json&limit=1&accept-language=en-US';
    
    public static final String METHOD_GET = 'GET';
    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String APPLICATION_JSON = 'application/json';
    public static final Integer SUCCESS_STATUS_CODE = 200;
    
    public static final String CLASS_STRING = '"class"';
    public static final String CLASSNAME_STRING = '"className"';
    public static final String TYPE_STRING = '"type"';
    public static final String TYPENAME_STRING = '"typeName"';
}